NODES = [
("docs_ci_github_actions_ci_workflows","GitHub Actions CI por repositorio","concept","/Volumes/Datos/dts-app-ecommerce/docs/CI_GITHUB_ACTIONS.md"),
("docs_ci_github_actions_postgis_pytest_ci","CI backend PostGIS + GDAL + pytest","concept","/Volumes/Datos/dts-app-ecommerce/docs/CI_GITHUB_ACTIONS.md"),
("docs_ci_github_actions_e2e_playwright_secrets","Secrets E2E Playwright en CI","concept","/Volumes/Datos/dts-app-ecommerce/docs/CI_GITHUB_ACTIONS.md"),
("docs_ci_github_actions_submodules_recursive","Checkout submodules recursive en CI","concept","/Volumes/Datos/dts-app-ecommerce/docs/CI_GITHUB_ACTIONS.md"),
("docs_ci_github_actions_realtime_smoke","Smoke realtime de CI","concept","/Volumes/Datos/dts-app-ecommerce/docs/CI_GITHUB_ACTIONS.md"),
("docs_deploy_docker_full_docker_stack","Despliegue 100% Docker en servidor","concept","/Volumes/Datos/dts-app-ecommerce/docs/DEPLOY_DOCKER.md"),
("docs_deploy_docker_entrypoint_sh","entrypoint.sh arranque automático","concept","/Volumes/Datos/dts-app-ecommerce/docs/DEPLOY_DOCKER.md"),
("docs_deploy_docker_repair_migration_tables","repair_migration_tables.py","concept","/Volumes/Datos/dts-app-ecommerce/docs/DEPLOY_DOCKER.md"),
("docs_deploy_docker_backend_media_volume","Volumen backend_media","concept","/Volumes/Datos/dts-app-ecommerce/docs/DEPLOY_DOCKER.md"),
("docs_deploy_railway_railway_services","Railway: postgis/Redis/Mailpit/DTS-backend","concept","/Volumes/Datos/dts-app-ecommerce/docs/DEPLOY_RAILWAY.md"),
("docs_deploy_railway_railway_toml","railway.toml + Dockerfile","concept","/Volumes/Datos/dts-app-ecommerce/docs/DEPLOY_RAILWAY.md"),
("docs_deploy_railway_celery_worker_beat","DTS-celery-worker/beat via toml","concept","/Volumes/Datos/dts-app-ecommerce/docs/DEPLOY_RAILWAY.md"),
("docs_deploy_railway_s3_media_option","S3 media en producción (Railway)","concept","/Volumes/Datos/dts-app-ecommerce/docs/DEPLOY_RAILWAY.md"),
("docs_estado_proyecto_cliente_feature_matrix","Matriz de avance por módulo de negocio","document","/Volumes/Datos/dts-app-ecommerce/docs/ESTADO_PROYECTO_CLIENTE.md"),
("docs_estado_proyecto_cliente_bff_layer","BFF capa Next.js /api/merchant","concept","/Volumes/Datos/dts-app-ecommerce/docs/ESTADO_PROYECTO_CLIENTE.md"),
("docs_customer_app_100_plan_plan_phases","Plan App Cliente 100% (fases C1–C5)","document","/Volumes/Datos/dts-app-ecommerce/docs/CUSTOMER_APP_100_PLAN.md"),
("docs_customer_app_100_plan_dts_design_system","Design system DTS (Manrope + widgets Dts*)","concept","/Volumes/Datos/dts-app-ecommerce/docs/CUSTOMER_APP_100_PLAN.md"),
("docs_customer_app_100_plan_backend_gap_apis","APIs backend nuevas (perfil, direcciones, delivery_address)","concept","/Volumes/Datos/dts-app-ecommerce/docs/CUSTOMER_APP_100_PLAN.md"),
("docs_evolucion_finanzas_contabilidad_pagos_countrypack","CountryPack (VE/CO/US) plan de cuentas","concept","/Volumes/Datos/dts-app-ecommerce/docs/EVOLUCION_FINANZAS_CONTABILIDAD_PAGOS.md"),
("docs_evolucion_finanzas_contabilidad_pagos_paymentmethodconfig","PaymentMethodConfig por tienda","concept","/Volumes/Datos/dts-app-ecommerce/docs/EVOLUCION_FINANZAS_CONTABILIDAD_PAGOS.md"),
("docs_evolucion_finanzas_contabilidad_pagos_financialmovement","FinancialMovement libro de ingresos","concept","/Volumes/Datos/dts-app-ecommerce/docs/EVOLUCION_FINANZAS_CONTABILIDAD_PAGOS.md"),
("docs_evolucion_finanzas_contabilidad_pagos_accounting_ledger","Ledger contable doble partida","concept","/Volumes/Datos/dts-app-ecommerce/docs/EVOLUCION_FINANZAS_CONTABILIDAD_PAGOS.md"),
("docs_evolucion_finanzas_contabilidad_pagos_postingengine","PostingEngine + BalanceValidator","concept","/Volumes/Datos/dts-app-ecommerce/docs/EVOLUCION_FINANZAS_CONTABILIDAD_PAGOS.md"),
("docs_evolucion_finanzas_contabilidad_pagos_pos_module","Módulo POS (venta mostrador)","concept","/Volumes/Datos/dts-app-ecommerce/docs/EVOLUCION_FINANZAS_CONTABILIDAD_PAGOS.md"),
("docs_evolucion_finanzas_contabilidad_pagos_non_processor_principle","DTS no procesa pagos (principio de diseño)","rationale","/Volumes/Datos/dts-app-ecommerce/docs/EVOLUCION_FINANZAS_CONTABILIDAD_PAGOS.md"),
("docs_evolucion_finanzas_contabilidad_pagos_paymentconfirmationprovider","PaymentConfirmationProvider (adapter pasarela)","concept","/Volumes/Datos/dts-app-ecommerce/docs/EVOLUCION_FINANZAS_CONTABILIDAD_PAGOS.md"),
("docs_fase4_blocks_fase4_blocks","Fase 4 bloques Flutter (4.0–4.9)","concept","/Volumes/Datos/dts-app-ecommerce/docs/FASE4_BLOCKS.md"),
("docs_fase4_blocks_driver_availability_api","API driver availability (T4.0.1)","concept","/Volumes/Datos/dts-app-ecommerce/docs/FASE4_BLOCKS.md"),
("docs_fase6_blocks_fase6_blocks","Fase 6 bloques (6.1–6.11)","concept","/Volumes/Datos/dts-app-ecommerce/docs/FASE6_BLOCKS.md"),
("docs_fase6_blocks_fotos_visibles","Fotos producto visibles (B6.11)","concept","/Volumes/Datos/dts-app-ecommerce/docs/FASE6_BLOCKS.md"),
("docs_fase7_blocks_fase7_blocks","Fase 7 bloques madurez admin (7.1–7.7)","concept","/Volumes/Datos/dts-app-ecommerce/docs/FASE7_BLOCKS.md"),
("docs_fase7_blocks_storeopeninghours","StoreOpeningHours (horarios)","concept","/Volumes/Datos/dts-app-ecommerce/docs/FASE7_BLOCKS.md"),
("docs_fase7_blocks_deliveryzone","DeliveryZone (zonas de entrega)","concept","/Volumes/Datos/dts-app-ecommerce/docs/FASE7_BLOCKS.md"),
("docs_fase7_blocks_promotion_lifecycle","Promociones lifecycle (Celery)","concept","/Volumes/Datos/dts-app-ecommerce/docs/FASE7_BLOCKS.md"),
("docs_firebase_tracking_channels_realtime","Django Channels tracking (canónico)","concept","/Volumes/Datos/dts-app-ecommerce/docs/FIREBASE_TRACKING.md"),
("docs_firebase_tracking_firestore_alternative","Firestore tracking alternativo (T5.5.1)","concept","/Volumes/Datos/dts-app-ecommerce/docs/FIREBASE_TRACKING.md"),
("docs_firebase_tracking_recordlocationusecase","RecordLocationUseCase","concept","/Volumes/Datos/dts-app-ecommerce/docs/FIREBASE_TRACKING.md"),
("docs_firebase_tracking_tracking_transport_flag","TRACKING_TRANSPORT feature flag","concept","/Volumes/Datos/dts-app-ecommerce/docs/FIREBASE_TRACKING.md"),
("docs_firebase_tracking_custom_claims","Custom Claims Firebase (uid ↔ CustomUser)","concept","/Volumes/Datos/dts-app-ecommerce/docs/FIREBASE_TRACKING.md"),
("docs_flutter_api_api_behavior","API móvil (base api.dtsdrop.com)","concept","/Volumes/Datos/dts-app-ecommerce/docs/FLUTTER_API.md"),
("docs_flutter_api_tracking_ws","Tracking WS /ws/orders/{id}/tracking/","concept","/Volumes/Datos/dts-app-ecommerce/docs/FLUTTER_API.md"),
("docs_flutter_api_auth_social","Auth móvil (JWT + Google/Apple Firebase)","concept","/Volumes/Datos/dts-app-ecommerce/docs/FLUTTER_API.md"),
("docs_flutter_api_sandbox_payments","Sandbox DTS pay (payment_status=paid)","concept","/Volumes/Datos/dts-app-ecommerce/docs/FLUTTER_API.md"),
("docs_flutter_api_driver_flow","Conductor endpoints (ofertas, earnings, KYC)","concept","/Volumes/Datos/dts-app-ecommerce/docs/FLUTTER_API.md"),
("docs_media_storage_storage_protocol","StorageBackend protocol","concept","/Volumes/Datos/dts-app-ecommerce/docs/MEDIA_STORAGE.md"),
("docs_media_storage_djangomediastorage","DjangoMediaStorage","concept","/Volumes/Datos/dts-app-ecommerce/docs/MEDIA_STORAGE.md"),
("docs_media_storage_local_backend","LocalStorageBackend","concept","/Volumes/Datos/dts-app-ecommerce/docs/MEDIA_STORAGE.md"),
("docs_media_storage_s3_backend","S3StorageBackend (boto3)","concept","/Volumes/Datos/dts-app-ecommerce/docs/MEDIA_STORAGE.md"),
("docs_media_storage_cloudinary_backend","CloudinaryStorageBackend","concept","/Volumes/Datos/dts-app-ecommerce/docs/MEDIA_STORAGE.md"),
("docs_media_storage_serve_media","SERVE_MEDIA + MEDIA_PUBLIC_BASE_URL","concept","/Volumes/Datos/dts-app-ecommerce/docs/MEDIA_STORAGE.md"),
("docs_merchant_onboarding_onboarding_flow","Onboarding comercio (landing → wizard → panel)","concept","/Volumes/Datos/dts-app-ecommerce/docs/MERCHANT_ONBOARDING.md"),
("docs_merchant_onboarding_email_verification","Verificación email (token 24h)","concept","/Volumes/Datos/dts-app-ecommerce/docs/MERCHANT_ONBOARDING.md"),
("docs_merchant_onboarding_vertical_catalog","Catálogo por vertical (comida/servicios/retail)","concept","/Volumes/Datos/dts-app-ecommerce/docs/MERCHANT_ONBOARDING.md"),
("docs_monorepo_submodule_layout","Monorepo con submodules (4 repos)","concept","/Volumes/Datos/dts-app-ecommerce/docs/MONOREPO.md"),
("docs_play_store_google_signin_play_app_signing_shas","SHA-1 Play App Signing / debug / upload","concept","/Volumes/Datos/dts-app-ecommerce/docs/PLAY_STORE_GOOGLE_SIGNIN.md"),
("docs_play_store_google_signin_gcp_apikey_restrictions","Google Cloud API key restrictions Android","concept","/Volumes/Datos/dts-app-ecommerce/docs/PLAY_STORE_GOOGLE_SIGNIN.md"),
("docs_play_store_google_signin_serverclientid","serverClientId (Web client type 3)","concept","/Volumes/Datos/dts-app-ecommerce/docs/PLAY_STORE_GOOGLE_SIGNIN.md"),
("docs_post_mvp_progress_post_mvp_sprints","Post-MVP sprints S0–S5","concept","/Volumes/Datos/dts-app-ecommerce/docs/POST_MVP_PROGRESS.md"),
("docs_post_mvp_progress_flexible_payments","Pagos flexibles S2 (payment-methods, sandbox, confirm)","concept","/Volumes/Datos/dts-app-ecommerce/docs/POST_MVP_PROGRESS.md"),
("docs_products_and_services_product_type","ProductType PHYSICAL/SERVICE","concept","/Volumes/Datos/dts-app-ecommerce/docs/PRODUCTS_AND_SERVICES.md"),
("docs_products_and_services_category_hierarchy","Categorías 2 niveles por tienda","concept","/Volumes/Datos/dts-app-ecommerce/docs/PRODUCTS_AND_SERVICES.md"),
("docs_products_and_services_stockvalidator","StockValidator (solo PHYSICAL)","concept","/Volumes/Datos/dts-app-ecommerce/docs/PRODUCTS_AND_SERVICES.md"),
("docs_products_and_services_service_order_flow","Flujo pedido servicio (sin SEARCHING_DRIVER)","concept","/Volumes/Datos/dts-app-ecommerce/docs/PRODUCTS_AND_SERVICES.md"),
("docs_products_and_services_serviceorderdetails","ServiceOrderDetails (dirección, agenda, notas)","concept","/Volumes/Datos/dts-app-ecommerce/docs/PRODUCTS_AND_SERVICES.md"),
("docs_progress_progress_tracking","PROGRESS.md tracking por tarea","document","/Volumes/Datos/dts-app-ecommerce/docs/PROGRESS.md"),
("docs_push_notifications_fcm_push_plan","Plan push FCM por estado","concept","/Volumes/Datos/dts-app-ecommerce/docs/PUSH_NOTIFICATIONS.md"),
("docs_push_notifications_devicetoken","DeviceToken model (T1.2.8)","concept","/Volumes/Datos/dts-app-ecommerce/docs/PUSH_NOTIFICATIONS.md"),
("docs_push_notifications_orderstatusmapper","OrderStatusNotificationMapper","concept","/Volumes/Datos/dts-app-ecommerce/docs/PUSH_NOTIFICATIONS.md"),
("docs_push_notifications_sendpush_task","SendPushUseCase + send_push_task","concept","/Volumes/Datos/dts-app-ecommerce/docs/PUSH_NOTIFICATIONS.md"),
("docs_push_notifications_driver_work_zone","Push conductores por zona de trabajo","concept","/Volumes/Datos/dts-app-ecommerce/docs/PUSH_NOTIFICATIONS.md"),
("docs_roadmap_six_phases","Roadmap 6 fases","document","/Volumes/Datos/dts-app-ecommerce/docs/ROADMAP.md"),
("docs_smoke_e2e_checklist_smoke_flows","Smoke E2E piloto (flujos A–E)","concept","/Volumes/Datos/dts-app-ecommerce/docs/SMOKE_E2E_CHECKLIST.md"),
("docs_store_release_checklist_store_publication","Checklist publicación App Store / Play","concept","/Volumes/Datos/dts-app-ecommerce/docs/STORE_RELEASE_CHECKLIST.md"),
("docs_store_release_checklist_android_google_signin","Android Google Sign-In checklist","concept","/Volumes/Datos/dts-app-ecommerce/docs/STORE_RELEASE_CHECKLIST.md"),
]